name: Deploy Inventory Manager

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy environment and docker files to server
        run: |
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            docker-compose.yml .env \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/namanjain34710/Inventory-Manager/

      - name: Deploy with Docker Compose on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            echo "---- Changing directory ----"
            cd /home/namanjain34710/Inventory-Manager

            echo "---- Stopping old containers ----"
            docker compose down || true

            echo "---- Pulling latest images (if any) ----"
            docker compose pull || true

            echo "---- Rebuilding and starting containers ----"
            docker compose up -d --build

            echo "---- Cleaning unused Docker resources ----"
            docker system prune -f

            echo "---- Deployment complete ----"
          EOF
