name: CI/CD Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set lowercase repository owner for GHCR
      - name: Set lowercase repository owner
        id: lowercase
        run: |
          lower_owner=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          echo "owner=$lower_owner" >> $GITHUB_OUTPUT

      # 3️⃣ Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Build & push Backend Docker image
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.owner }}/inventory-backend:latest
          target: production

      # 5️⃣ Build & push Frontend Docker image
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.owner }}/inventory-frontend:latest
          target: production
          build-args: |
            API_URL=${{ secrets.API_URL }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      # 3️⃣ Copy docker-compose.yml and .env to server
      - name: Copy docker-compose files to server
        run: |
          scp -i ~/.ssh/id_ed25519 docker-compose.yml .env \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/inventory-manager

      # 4️⃣ Deploy using SSH
      - name: Deploy to Production
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
            mkdir -p ~/inventory-manager
            cd ~/inventory-manager

            # Login to GitHub Container Registry
            echo "${GITHUB_TOKEN}" | docker login ghcr.io -u $USER --password-stdin

            # Pull latest images
            docker-compose pull

            # Start containers
            docker-compose up -d --remove-orphans

            # Optional: prune dangling images
            docker image prune -f

            # Show container status
            docker ps -a

            # Optional: view logs
            echo "=== Backend Logs ==="
            docker logs inventory-backend || true
            echo "=== Frontend Logs ==="
            docker logs inventory-frontend || true
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
