name: CI/CD Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set lowercase repository owner for GHCR
      - name: Set lowercase repository owner
        id: lowercase
        run: |
          lower_owner=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          echo "owner=$lower_owner" >> $GITHUB_OUTPUT
          echo "Lowercase owner: $lower_owner"

      # 3️⃣ Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Build & push Backend Docker image
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.owner }}/inventory-backend:latest
          target: production

      # 5️⃣ Build & push Frontend Docker image
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.owner }}/inventory-frontend:latest
          target: production
          build-args: |
            API_URL=${{ secrets.API_URL }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Copy docker-compose.yml and .env to server
      - name: Copy docker-compose files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "${{ secrets.SERVER_HOST }}"
          username: "${{ secrets.SERVER_USER }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          source: "docker-compose.yml,.env"
          target: "/home/${{ secrets.SERVER_USER }}/inventory-manager"

      # 3️⃣ Deploy using SSH
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "${{ secrets.SERVER_HOST }}"
          username: "${{ secrets.SERVER_USER }}"
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          # Optional: retry up to 3 times in case of temporary network issues
          retry: 3
          script: |
            set -e

            # Create project directory if not exists
            mkdir -p /home/${{ secrets.SERVER_USER }}/inventory-manager
            cd /home/${{ secrets.SERVER_USER }}/inventory-manager

            # Login to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Pull latest Docker images
            docker-compose pull

            # Start containers (remove orphans)
            docker-compose up -d --remove-orphans

            # Optional: prune only dangling images for this project
            docker image prune -f --filter "label=project=inventory"

            # Show container status
            docker ps -a

            # Optional: check logs of Backend and Frontend
            echo "=== Backend Logs ==="
            docker logs inventory-backend || true
            echo "=== Frontend Logs ==="
            docker logs inventory-frontend || true
